name: Build docker images

on:
    push:
        # Publish `master` as Docker `latest` image.
        branches:
            - master

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            -
                name: Build images
                run: |
                    VERSION=latest
                    TAG=${{ steps.previous_tag.outputs.tag }}

                    docker pull rector/rector || true
                    docker build . --target rector --cache-from rector/rector --tag rector/rector:$VERSION
                    docker build . --target rector-secured --cache-from rector/rector --tag rector/rector-secured:$VERSION

                    docker build . --target rector --cache-from rector/rector --tag rector/rector:$TAG
                    docker build . --target rector-secured --cache-from rector/rector --tag rector/rector-secured:$TAG

            -
                name: Log into registry
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            -
                name: Push Images
                run: docker push rector/rector

            -
                name: Push Secured Images
                run: docker push rector/rector-secured
